/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hawkfranklin.aura.ui.theme

import androidx.compose.ui.graphics.Color

// Aura palette (gold + cyan on deep-void)
val primaryLight = Color(0xFFD9A441)
val onPrimaryLight = Color(0xFF2B1E09)
val primaryContainerLight = Color(0xFFFFE3B3)
val onPrimaryContainerLight = Color(0xFF3B2B10)
val secondaryLight = Color(0xFF22D3EE)
val onSecondaryLight = Color(0xFF00323B)
val secondaryContainerLight = Color(0xFFB7F3FF)
val onSecondaryContainerLight = Color(0xFF004954)
val tertiaryLight = Color(0xFF7C5AE6)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE6DCFF)
val onTertiaryContainerLight = Color(0xFF2B1C4D)
val errorLight = Color(0xFFB3261E)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFF9DEDC)
val onErrorContainerLight = Color(0xFF8C1D18)
val backgroundLight = Color(0xFFF7F7F8)
val onBackgroundLight = Color(0xFF141416)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF141416)
val surfaceVariantLight = Color(0xFFE7E7EA)
val onSurfaceVariantLight = Color(0xFF45464A)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F2F4)
val surfaceContainerLight = Color(0xFFE9EAEE)
val surfaceContainerHighLight = Color(0xFFE1E3E8)
val surfaceContainerHighestLight = Color(0xFFDADDE3)
val inverseSurfaceLight = Color(0xFF2B2B2F)
val inverseOnSurfaceLight = Color(0xFFF1F1F2)
val outlineLight = Color(0xFF7A7C80)
val outlineVariantLight = Color(0xFFC7C9CF)
val inversePrimaryLight = Color(0xFFFFDFA6)
val surfaceDimLight = Color(0xFFD8DADF)
val surfaceBrightLight = Color(0xFFFFFFFF)
val scrimLight = Color(0xFF000000)

val primaryDark = Color(0xFFD9A441)
val onPrimaryDark = Color(0xFF2B1E09)
val primaryContainerDark = Color(0xFF4A3714)
val onPrimaryContainerDark = Color(0xFFFFE3B3)
val secondaryDark = Color(0xFF22D3EE)
val onSecondaryDark = Color(0xFF00343C)
val secondaryContainerDark = Color(0xFF0D3A44)
val onSecondaryContainerDark = Color(0xFFB7F3FF)
val tertiaryDark = Color(0xFFBFA7FF)
val onTertiaryDark = Color(0xFF2A1B4D)
val tertiaryContainerDark = Color(0xFF3A2B5E)
val onTertiaryContainerDark = Color(0xFFE6DCFF)
val errorDark = Color(0xFFF2B8B5)
val onErrorDark = Color(0xFF601410)
val errorContainerDark = Color(0xFF8C1D18)
val onErrorContainerDark = Color(0xFFF9DEDC)
val backgroundDark = Color(0xFF020617)
val onBackgroundDark = Color(0xFFE5E7EB)
val surfaceDark = Color(0xFF0B1220)
val onSurfaceDark = Color(0xFFE5E7EB)
val surfaceVariantDark = Color(0xFF2D2F36)
val onSurfaceVariantDark = Color(0xFFC7C9CF)
val surfaceContainerLowestDark = Color(0xFF0A0F1A)
val surfaceContainerLowDark = Color(0xFF101827)
val surfaceContainerDark = Color(0xFF151C2D)
val surfaceContainerHighDark = Color(0xFF1B2336)
val surfaceContainerHighestDark = Color(0xFF222B40)
val inverseSurfaceDark = Color(0xFFE5E7EB)
val inverseOnSurfaceDark = Color(0xFF1F2937)
val outlineDark = Color(0xFF8B8F98)
val outlineVariantDark = Color(0xFF3A3D46)
val inversePrimaryDark = Color(0xFFFFDFA6)
val surfaceDimDark = Color(0xFF0B1220)
val surfaceBrightDark = Color(0xFF2B344B)
val scrimDark = Color(0xFF000000)

// Aura theme palette (purple/void)
val primaryAura = Color(0xFF6366F1)
val onPrimaryAura = Color(0xFFFFFFFF)
val primaryContainerAura = Color(0xFF312E81)
val onPrimaryContainerAura = Color(0xFFE0E7FF)
val secondaryAura = Color(0xFFA855F7)
val onSecondaryAura = Color(0xFFFFFFFF)
val secondaryContainerAura = Color(0xFF4C1D95)
val onSecondaryContainerAura = Color(0xFFE9D5FF)
val tertiaryAura = Color(0xFF818CF8)
val onTertiaryAura = Color(0xFF0F172A)
val tertiaryContainerAura = Color(0xFF1E1B4B)
val onTertiaryContainerAura = Color(0xFFE0E7FF)
val errorAura = Color(0xFFFCA5A5)
val onErrorAura = Color(0xFF4C0519)
val errorContainerAura = Color(0xFF3B0A1E)
val onErrorContainerAura = Color(0xFFFEE2E2)
val backgroundAura = Color(0xFF020617)
val onBackgroundAura = Color(0xFFE2E8F0)
val surfaceAura = Color(0xFF0F172A)
val onSurfaceAura = Color(0xFFE2E8F0)
val surfaceVariantAura = Color(0xFF1E293B)
val onSurfaceVariantAura = Color(0xFF94A3B8)
val surfaceContainerLowestAura = Color(0xFF0A0F1A)
val surfaceContainerLowAura = Color(0xFF0D1422)
val surfaceContainerAura = Color(0xFF121A2B)
val surfaceContainerHighAura = Color(0xFF182236)
val surfaceContainerHighestAura = Color(0xFF1E2A42)
val inverseSurfaceAura = Color(0xFFE2E8F0)
val inverseOnSurfaceAura = Color(0xFF0F172A)
val outlineAura = Color(0xFF334155)
val outlineVariantAura = Color(0xFF1E293B)
val inversePrimaryAura = Color(0xFFC7D2FE)
val surfaceDimAura = Color(0xFF0B1220)
val surfaceBrightAura = Color(0xFF1E293B)
val scrimAura = Color(0xFF000000)
